### ISSUE TITLE
Home Assistant MQTT card

### ISSUE THREAD

**Issue by dennislv** [Dilbert66/esphome-vistaECP#88]
Are there instructions for adding the alarm card into Home Assistant? I'm using the MQTT version. 

As far as the interface goes, I use MQTT Explorer I can see the updates, as well as manually publish to /vista/Set/Cmd without problem.

Thanks in advance

**Comment by Dilbert66** [comment]
Home assistant unfortunately does not make it intuitive to do that.  Here's a quick rundown:

Put the alarm-keypad-card.js and *.mp3 files into your config/www folder.
Add a reference to alarm-keypad-card.js in Lovelace. There’s two way to do that:
Using UI: Configuration → Lovelace Dashboards → Resources Tab → Click Plus button → Set Url as /local/alarm-keypad-card.js → Set Resource type as JavaScript Module. 
Note: If you do not see the Resources Tab, you will need to enable Advanced Mode in your User Profile
Using YAML: Add following code to lovelace section
resources:
    - url: /local/alarm-keypad-card.js
      type: module

**Comment by Dilbert66** [comment]
No sure why you cant hear them. Try doing an F5 on the dashboard to force a reload to see if that helps.  All that's needed is to have the files in the local directory which you already have.   They are not really necessary anyhow, just an added feature that someone had requested.   Sometimes I find the beeps more annoying than anything since I test a few different panels with different partitions.
